P=[1,2,3,4,5,6,7,8,9,2,15,"priyanka","kapse","apple","car"]

p.append(10)
p.clear()
R=P.copy()
R=P.count(2)
R=P.count("priyanka")
T=["sum","now","fine","see",100,200]
P.extend(T)
R=P.index("priyanka")
P.insert(10,"name")
print(R)
P.pop(14)
P.remove(9)
P.reverse()
X=["apple","van","sign","no","bat","zebra","cat"]
X.sort()
print(X)
print(P)
