
mylist=[1,23,45,"Priyanka",2,1,"Apple","College"]
print(mylist)
print(mylist[0])
print(mylist[1])
print(mylist[2])
print(mylist[3])
print(mylist[4])
print(mylist[5])
print(mylist[6])
print(mylist[7])

print(mylist[-1])
print(mylist[-2])
print(mylist[-3])
print(mylist[-4])
print(mylist[-5])
print(mylist[-6])
print(mylist[-7])
print(mylist[-8])


print(mylist[1:])
print(mylist[2:])
print(mylist[3:])
print(mylist[4:])
print(mylist[5:])
print(mylist[6:])
print(mylist[7:])
print(mylist[:])
print(mylist[4:7])
print(mylist[0:4])
print(mylist[-4:-1])
print(mylist[-5:-3])
